name: emoticore
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  fl_chart: ^1.1.1
  intl: ^0.20.2
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  lottie: ^3.1.2
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/brain_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/brain_icon.png
    - assets/
    - assets/avatars/
    - assets/animations/

flutter_native_splash:
  # This color will be shown instantly, replacing the black/white screen.
  # Use your app's main background color.
  color: "#FFFFFF" # Your tealBlue color

  # (Optional but recommended)
  # This shows your logo instantly on top of the color.
  image: assets/brain_icon.png 

  # Android 12+ has a special splash screen. This configures it.
  android_12:
    image: assets/brain_icon.png
    color: "#FFFFFF"

  # iOS Configuration
  ios_content_mode: scaleAspectFit